// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"gin-template/api_v2/controller"
	"gin-template/api_v2/repository"
	"gin-template/api_v2/service"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	config := GetEnvVariables()
	dbStore := ConnectToDB(config)
	accountRpositoryImp := repository.AccountRepositoryImpInit(dbStore)
	accountServiceImpl := service.AccountServiceImplInit(accountRpositoryImp)
	accountControllerImpl := controller.AccountControllerImplInit(accountServiceImpl)
	initialization := NewInitialization(config, accountControllerImpl)
	return initialization
}

// injector.go:

var envVariables = wire.NewSet(GetEnvVariables)

var store = wire.NewSet(ConnectToDB)

var accountRepo = wire.NewSet(repository.AccountRepositoryImpInit)

var accountSvc = wire.NewSet(service.AccountServiceImplInit)

var accountCtrl = wire.NewSet(controller.AccountControllerImplInit)
